version: "3"
services:
  app:
    env_file:
      - .env
    container_name: be-booking-room
    restart: always
    build: .
    command: yarn start:prod
    ports:
      - "3002:$PORT"
      - "8081:8081"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
